---

- name: Add clubhouse credential
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    credential_type: clubhouse
    description: "{{ item.description|default('', true) }}"
    organization: "{{ tower.organisation }}"
    inputs:
      token: "{{ item.token }}"

- name: Grant team access to the clubhouse credential ({{ item.name }})
  command: >-
    tower-cli role grant
    --team '{{ credential_team }}'
    --type admin
    --credential '{{ item.name }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ item.teams }}"
  loop_control:
    loop_var: credential_team
  when: item.teams is defined
