---

- name: Add scm credential
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    kind: scm
    description: "{{ item.description|default('', true) }}"
    organization: "{{ tower.organisation }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"

- name: Grant team access to the scm credential ({{ item.name }})
  command: >-
    tower-cli role grant
    --team '{{ credential_team }}'
    --type admin
    --credential '{{ item.name }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ item.teams }}"
  loop_control:
    loop_var: credential_team
  when: item.teams is defined
