---

# First, add the AWS and kubernetes credentials that should
# be available as existing environment variables.
# That'll be an AWS credential used for the cluster
# and a Kubernetes credential for the control plane.

- block:

  - name: Check AWS credential
    assert:
      that: tower_cluster_aws_secret_access_key|length > 0

  - name: Add AWS credential
    include_tasks: add-credential-aws.yaml
    vars:
      item:
        name: aws (SELF)
        description: The AWX cluster AWS IAM User
        aws_access_key_id: "{{ tower_cluster_aws_access_key_id }}"
        aws_secret_access_key: "{{ tower_cluster_aws_secret_access_key }}"

  - name: Grant team access to the AWS credential
    command: >-
      tower-cli role grant
      --team '{{ item }}'
      --type admin
      --credential 'aws (SELF)'
    register: cmd_result
    changed_when: "'changed: false' not in cmd_result.stdout"
    loop: "{{ tower.teams }}"
    when: tower.teams is defined

  when: tower_cluster_aws_access_key_id|length > 0

- block:

  - name: Check Kubernetes credential
    assert:
      that: tower_cluster_k8s_auth_api_key|length > 0

  - name: Add Kubernetes credential
    include_tasks: add-credential-kubernetes.yaml
    vars:
      item:
        name: k8s (SELF)
        description: The AWX cluster control plane credentials
        host: "{{ tower_cluster_k8s_auth_host }}"
        api_key: "{{ tower_cluster_k8s_auth_api_key }}"
        verify_ssl: "{{ tower_cluster_k8s_auth_veify_ssl }}"

  - name: Grant team access to the Kubernetes credential
    command: >-
      tower-cli role grant
      --team '{{ item }}'
      --type admin
      --credential 'k8s (SELF)'
    register: cmd_result
    changed_when: "'changed: false' not in cmd_result.stdout"
    loop: "{{ tower.teams }}"
    when: tower.teams is defined

  when: tower_cluster_k8s_auth_host|length > 0

# Now add credentials defined in the user's configuration.
# This is the list of definitions in the 'tower -> credentials' block...

- name: Add credentials
  include_tasks: add-credential-{{ item.kind }}.yaml
  loop: "{{ tower.credentials }}"
  when: tower.credentials is defined
