---

- name: Add okd credential
  awx.awx.tower_credential:
    name: "{{ item.name }}"
    credential_type: okd
    description: "{{ item.description|default('', true) }}"
    organization: "{{ tower.organisation }}"
    inputs:
      name: "{{ item.name }}"
      master_hostname: "{{ item.master_hostname }}"
      route_basename: "{{ item.route_basename }}"
      admin: "{{ item.admin }}"
      admin_password: "{{ item.admin_password }}"
      user: "{{ item.user }}"
      user_password: "{{ item.user_password }}"

- name: Grant team access to the okd credential ({{ item.name }})
  command: >-
    tower-cli role grant
    --team '{{ credential_team }}'
    --type admin
    --credential '{{ item.name }}'
  register: cmd_result
  changed_when: "'changed: false' not in cmd_result.stdout"
  loop: "{{ item.teams }}"
  loop_control:
    loop_var: credential_team
  when: item.teams is defined
